name: example
description: "Example app for the drift_crdt package."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  drift: ^2.28.1
  drift_crdt:
    path: ../
  flutter:
    sdk: flutter
  path: ^1.9.1
  path_provider: ^2.1.5
  provider: ^6.1.2
  sqlite3: ^2.9.0
  sqlite3_flutter_libs: ^0.5.39
  uuid: ^4.5.1

dev_dependencies:
  build_runner: ^2.4.13
  drift_dev: ^2.9.0

  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  very_good_analysis: ^8.0.0

flutter:
  uses-material-design: true
